//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSM.DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Content
    {
        public int InfoID { get; set; }
        public System.DateTime DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public string KeyID { get; set; }
        public string Title { get; set; }
        public string Destination { get; set; }
        public string HtmlContent { get; set; }
        public string LanguageID { get; set; }
    }
}
