//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSM.DataService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class SOCCER_SCHEDULEEntities : DbContext
    {
        public SOCCER_SCHEDULEEntities()
            : base("name=SOCCER_SCHEDULEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Content> Contents { get; set; }
        public DbSet<League> Leagues { get; set; }
        public DbSet<LeagueTeam> LeagueTeams { get; set; }
        public DbSet<List> Lists { get; set; }
        public DbSet<Match> Matches { get; set; }
        public DbSet<Stage> Stages { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<Team> Teams { get; set; }
    
        public virtual ObjectResult<Match_GetList_Result> Match_GetList(string groupID)
        {
            var groupIDParameter = groupID != null ?
                new ObjectParameter("GroupID", groupID) :
                new ObjectParameter("GroupID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Match_GetList_Result>("Match_GetList", groupIDParameter);
        }
    }
}
