//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSM.DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeagueTeam
    {
        public string LeagueID { get; set; }
        public string TeamID { get; set; }
        public string GroupID { get; set; }
        public short Rank { get; set; }
        public short Point { get; set; }
        public short Won { get; set; }
        public short Lost { get; set; }
        public short Drawn { get; set; }
        public short GoalLostDiff { get; set; }
        public short GoalsScored { get; set; }
        public short GoalConceded { get; set; }
    }
}
