//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSM.DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class League
    {
        public string LeagueID { get; set; }
        public string LeagueType { get; set; }
        public string CountryID { get; set; }
        public bool QualifiersRound { get; set; }
        public bool CompentitionRound { get; set; }
        public bool SemiFinalRound { get; set; }
        public bool FinalMatch { get; set; }
        public bool SubordinateMatch { get; set; }
        public byte TimeZone { get; set; }
    }
}
