//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSM.DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class List
    {
        public int ListID { get; set; }
        public int OrderNo { get; set; }
        public string SourceKeyID { get; set; }
        public string LanguageID { get; set; }
        public string Source { get; set; }
        public string Text { get; set; }
    }
}
