//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSM.DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stage
    {
        public string StageID { get; set; }
        public string CountryID { get; set; }
        public string ProvinceID { get; set; }
    }
}
